export const LOAD_POSTS_REQUEST = "LOAD_POST_REQUEST";
export const LOAD_POSTS = "LOAD_POSTS";

export const LOAD_COMMENTS_REQUEST = "LOAD_COMMENTS_REQUEST"
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS"
export const SUBMIT_COMMENT_REQUEST = "SUBMIT_COMMENT_REQUEST"
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS"